### ISSUE TITLE
Reset countdown clock

### ISSUE THREAD

**Issue by wardvanderput** [storecore/storecore.github.io#1]
The JavaScript countdown clock on the homepage currently only includes a date:

```
var deadline = '2017-01-31';
```

Therefore the clock counts down to midnight 00:00:00 hours in UTC. At that time, it is still 23:00 on the preceding monday in Central European Time (The Netherlands, Belgium, France, Italy, Spain et cetera). I would like to suggest we move the clock to noon 12:00 UTC and 13:00 CET, because this seems like a much more approriate time for releases.

**Comment by tvb** [comment]
Are we going to launch?? :rocket:

Something like:
'''
//A: RECORDS TODAY'S Date And Time
$today = time();

//B: RECORDS Date And Time OF YOUR EVENT
$event = mktime(0,0,0,12,25,2006);

//C: COMPUTES THE DAYS UNTIL THE EVENT.
$countdown = round(($event - $today)/86400);

//D: DISPLAYS COUNTDOWN UNTIL EVENT
echo "$countown days until launch";

?>
'''
